/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FRAMES;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Dell
 */
public class SuperAdmin extends javax.swing.JFrame {

    /**
     * Creates new form Admission_System
     */
    public SuperAdmin() {
        
        initComponents();
         java.awt.Toolkit kit=this.getToolkit();
        java.awt.Dimension d=kit.getScreenSize();
        this.setBounds(0,0,d.width,d.height);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        facultyButton = new javax.swing.JButton();
        departmentButton = new javax.swing.JButton();
        programButton = new javax.swing.JButton();
        studentButton = new javax.swing.JButton();
        batchButton = new javax.swing.JButton();
        seatListDetailButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        partButton = new javax.swing.JButton();
        seatListButton = new javax.swing.JButton();
        studentPartButton = new javax.swing.JButton();
        notifactionButton = new javax.swing.JButton();
        schemePartButton = new javax.swing.JButton();
        schemeSemesterButton = new javax.swing.JButton();
        schemeDetailButton = new javax.swing.JButton();
        schemeButton = new javax.swing.JButton();
        ledgerButton = new javax.swing.JButton();
        ledgerDetailButton = new javax.swing.JButton();
        ledgerDetailSummaryButton1 = new javax.swing.JButton();
        TeacherButton1 = new javax.swing.JButton();
        timeTableButton2 = new javax.swing.JButton();
        AssignmentButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SINDH UNIVERSITY");
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setName("SINDH UNIVERSITY"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(" U N I V E R S I T Y   O F   S I N D H");
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, 0, 1920, 80));

        facultyButton.setBackground(new java.awt.Color(0, 0, 0));
        facultyButton.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 24)); // NOI18N
        facultyButton.setForeground(new java.awt.Color(255, 255, 255));
        facultyButton.setText("FACULTY");
        facultyButton.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 0, 10, 0, new java.awt.Color(0, 0, 0)));
        facultyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facultyButtonActionPerformed(evt);
            }
        });
        getContentPane().add(facultyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 330, 50));

        departmentButton.setBackground(new java.awt.Color(0, 0, 0));
        departmentButton.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 24)); // NOI18N
        departmentButton.setForeground(new java.awt.Color(255, 255, 255));
        departmentButton.setText("DEPARTMENT");
        departmentButton.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 0, 10, 0, new java.awt.Color(0, 0, 0)));
        departmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentButtonActionPerformed(evt);
            }
        });
        getContentPane().add(departmentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 90, 280, 50));

        programButton.setBackground(new java.awt.Color(0, 0, 0));
        programButton.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 24)); // NOI18N
        programButton.setForeground(new java.awt.Color(255, 255, 255));
        programButton.setText("PROGRAM");
        programButton.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 0, 10, 0, new java.awt.Color(0, 0, 0)));
        programButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                programButtonActionPerformed(evt);
            }
        });
        getContentPane().add(programButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 90, 360, 50));

        studentButton.setBackground(new java.awt.Color(0, 0, 0));
        studentButton.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 24)); // NOI18N
        studentButton.setForeground(new java.awt.Color(255, 255, 255));
        studentButton.setText("STUDENT");
        studentButton.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 0, 10, 0, new java.awt.Color(0, 0, 0)));
        studentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentButtonActionPerformed(evt);
            }
        });
        getContentPane().add(studentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 160, 360, 50));

        batchButton.setBackground(new java.awt.Color(0, 0, 0));
        batchButton.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 24)); // NOI18N
        batchButton.setForeground(new java.awt.Color(255, 255, 255));
        batchButton.setText("BATCH");
        batchButton.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 0, 10, 0, new java.awt.Color(0, 0, 0)));
        batchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batchButtonActionPerformed(evt);
            }
        });
        getContentPane().add(batchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 330, 50));

        seatListDetailButton.setBackground(new java.awt.Color(0, 0, 0));
        seatListDetailButton.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 24)); // NOI18N
        seatListDetailButton.setForeground(new java.awt.Color(255, 255, 255));
        seatListDetailButton.setText("SEAT LIST DETAIL");
        seatListDetailButton.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 0, 10, 0, new java.awt.Color(0, 0, 0)));
        seatListDetailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatListDetailButtonActionPerformed(evt);
            }
        });
        getContentPane().add(seatListDetailButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 230, 280, 50));

        exitButton.setBackground(new java.awt.Color(255, 0, 0));
        exitButton.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        exitButton.setForeground(new java.awt.Color(255, 255, 255));
        exitButton.setText("EXIT");
        exitButton.setToolTipText("");
        exitButton.setBorder(null);
        exitButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 690, 510, -1));

        partButton.setBackground(new java.awt.Color(0, 0, 0));
        partButton.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 24)); // NOI18N
        partButton.setForeground(new java.awt.Color(255, 255, 255));
        partButton.setText("PART");
        partButton.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 0, 10, 0, new java.awt.Color(0, 0, 0)));
        partButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partButtonActionPerformed(evt);
            }
        });
        getContentPane().add(partButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 160, 280, 50));

        seatListButton.setBackground(new java.awt.Color(0, 0, 0));
        seatListButton.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 24)); // NOI18N
        seatListButton.setForeground(new java.awt.Color(255, 255, 255));
        seatListButton.setText("SEAT LIST");
        seatListButton.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 0, 10, 0, new java.awt.Color(0, 0, 0)));
        seatListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatListButtonActionPerformed(evt);
            }
        });
        getContentPane().add(seatListButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 330, 50));

        studentPartButton.setBackground(new java.awt.Color(0, 0, 0));
        studentPartButton.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 24)); // NOI18N
        studentPartButton.setForeground(new java.awt.Color(255, 255, 255));
        studentPartButton.setText("STUDENT REGISTRATION");
        studentPartButton.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 0, 10, 0, new java.awt.Color(0, 0, 0)));
        studentPartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentPartButtonActionPerformed(evt);
            }
        });
        getContentPane().add(studentPartButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 230, 360, 50));

        notifactionButton.setBackground(new java.awt.Color(0, 0, 0));
        notifactionButton.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 24)); // NOI18N
        notifactionButton.setForeground(new java.awt.Color(255, 255, 255));
        notifactionButton.setText("ADD NOTIFICATION  ");
        notifactionButton.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 0, 10, 0, new java.awt.Color(0, 0, 0)));
        notifactionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notifactionButtonActionPerformed(evt);
            }
        });
        getContentPane().add(notifactionButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 590, 1010, 50));

        schemePartButton.setBackground(new java.awt.Color(0, 0, 0));
        schemePartButton.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 24)); // NOI18N
        schemePartButton.setForeground(new java.awt.Color(255, 255, 255));
        schemePartButton.setText("SCHEME PART");
        schemePartButton.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 0, 10, 0, new java.awt.Color(0, 0, 0)));
        schemePartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schemePartButtonActionPerformed(evt);
            }
        });
        getContentPane().add(schemePartButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 300, 280, 50));

        schemeSemesterButton.setBackground(new java.awt.Color(0, 0, 0));
        schemeSemesterButton.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 24)); // NOI18N
        schemeSemesterButton.setForeground(new java.awt.Color(255, 255, 255));
        schemeSemesterButton.setText("SCHEME SEMESTER");
        schemeSemesterButton.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 0, 10, 0, new java.awt.Color(0, 0, 0)));
        schemeSemesterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schemeSemesterButtonActionPerformed(evt);
            }
        });
        getContentPane().add(schemeSemesterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 300, 360, 50));

        schemeDetailButton.setBackground(new java.awt.Color(0, 0, 0));
        schemeDetailButton.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 24)); // NOI18N
        schemeDetailButton.setForeground(new java.awt.Color(255, 255, 255));
        schemeDetailButton.setText("SCHEME  DETAILS");
        schemeDetailButton.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 0, 10, 0, new java.awt.Color(0, 0, 0)));
        schemeDetailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schemeDetailButtonActionPerformed(evt);
            }
        });
        getContentPane().add(schemeDetailButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, 330, 50));

        schemeButton.setBackground(new java.awt.Color(0, 0, 0));
        schemeButton.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 24)); // NOI18N
        schemeButton.setForeground(new java.awt.Color(255, 255, 255));
        schemeButton.setText("SCHEME");
        schemeButton.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 0, 10, 0, new java.awt.Color(0, 0, 0)));
        schemeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schemeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(schemeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 330, 50));

        ledgerButton.setBackground(new java.awt.Color(0, 0, 0));
        ledgerButton.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 24)); // NOI18N
        ledgerButton.setForeground(new java.awt.Color(255, 255, 255));
        ledgerButton.setText("LEDGER");
        ledgerButton.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 0, 10, 0, new java.awt.Color(0, 0, 0)));
        ledgerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ledgerButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ledgerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 370, 280, 50));

        ledgerDetailButton.setBackground(new java.awt.Color(0, 0, 0));
        ledgerDetailButton.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 24)); // NOI18N
        ledgerDetailButton.setForeground(new java.awt.Color(255, 255, 255));
        ledgerDetailButton.setText("LEDGER  DETAIL");
        ledgerDetailButton.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 0, 10, 0, new java.awt.Color(0, 0, 0)));
        ledgerDetailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ledgerDetailButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ledgerDetailButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 370, 360, 50));

        ledgerDetailSummaryButton1.setBackground(new java.awt.Color(0, 0, 0));
        ledgerDetailSummaryButton1.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 24)); // NOI18N
        ledgerDetailSummaryButton1.setForeground(new java.awt.Color(255, 255, 255));
        ledgerDetailSummaryButton1.setText("LEDGER  DETAIL  SUMMARY");
        ledgerDetailSummaryButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 0, 10, 0, new java.awt.Color(0, 0, 0)));
        ledgerDetailSummaryButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ledgerDetailSummaryButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(ledgerDetailSummaryButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, 330, 50));

        TeacherButton1.setBackground(new java.awt.Color(0, 0, 0));
        TeacherButton1.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 24)); // NOI18N
        TeacherButton1.setForeground(new java.awt.Color(255, 255, 255));
        TeacherButton1.setText("TEACHERS");
        TeacherButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 0, 10, 0, new java.awt.Color(0, 0, 0)));
        TeacherButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeacherButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(TeacherButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 440, 280, 50));

        timeTableButton2.setBackground(new java.awt.Color(0, 0, 0));
        timeTableButton2.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 24)); // NOI18N
        timeTableButton2.setForeground(new java.awt.Color(255, 255, 255));
        timeTableButton2.setText("TIME TABLE");
        timeTableButton2.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 0, 10, 0, new java.awt.Color(0, 0, 0)));
        timeTableButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeTableButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(timeTableButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 440, 360, 50));

        AssignmentButton3.setBackground(new java.awt.Color(0, 0, 0));
        AssignmentButton3.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 24)); // NOI18N
        AssignmentButton3.setForeground(new java.awt.Color(255, 255, 255));
        AssignmentButton3.setText("ASSIGNMENT");
        AssignmentButton3.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 0, 10, 0, new java.awt.Color(0, 0, 0)));
        AssignmentButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssignmentButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(AssignmentButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 520, 1010, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Desktop\\DEPARTMENT_LIVE_UPDATE_SYSTEM\\src\\image\\download (1).jpeg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void facultyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facultyButtonActionPerformed
        try {
            // TODO add your handling code here:
            FacultyFrame ob = new FacultyFrame();
            ob.show();
        } catch (Exception ex) {
            Logger.getLogger(SuperAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_facultyButtonActionPerformed

    private void departmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentButtonActionPerformed
        // TODO add your handling code here:
        try{
        DepartmentFrame ob=new DepartmentFrame();
        ob.show();
        }catch(Exception e){
            e.printStackTrace();
        }

    }//GEN-LAST:event_departmentButtonActionPerformed

    private void programButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_programButtonActionPerformed
        // TODO add your handling code here:
        ProgramFrame ob=new ProgramFrame();
        ob.show();
        
    }//GEN-LAST:event_programButtonActionPerformed

    private void batchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batchButtonActionPerformed
        // TODO add your handling code here:
        
        BatchFrame ob=new BatchFrame();
        ob.show();
    }//GEN-LAST:event_batchButtonActionPerformed

    private void studentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentButtonActionPerformed
        // TODO add your handling code here:
        StudentFrame ob=new StudentFrame();
        ob.show();
    }//GEN-LAST:event_studentButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        //System.exit(0);
        Login ob =new Login();
        ob.show();
        this.hide();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void seatListDetailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatListDetailButtonActionPerformed
        // TODO add your handling code here:
        SeatListDetailFrame ob=new SeatListDetailFrame();
        ob.show();
        
       
    }//GEN-LAST:event_seatListDetailButtonActionPerformed

    private void partButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partButtonActionPerformed
        // TODO add your handling code here:
        PartFrame ob=new PartFrame();
        ob.show();
        
    }//GEN-LAST:event_partButtonActionPerformed

    private void studentPartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentPartButtonActionPerformed
        // TODO add your handling code here:
        StudentRegistrationFrame ob=new StudentRegistrationFrame();
        ob.show();
    }//GEN-LAST:event_studentPartButtonActionPerformed

    private void seatListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatListButtonActionPerformed
        // TODO add your handling code here
        
        SeatListFrame ob=new SeatListFrame();
        ob.show();
        
    }//GEN-LAST:event_seatListButtonActionPerformed

    private void notifactionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notifactionButtonActionPerformed
        // TODO add your handling code here:
      Notification_Of_Class_Frame ob=new Notification_Of_Class_Frame();
        ob.show();
    }//GEN-LAST:event_notifactionButtonActionPerformed

    private void schemePartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schemePartButtonActionPerformed
        // TODO add your handling code here:
        SchemePartFrame ob=new SchemePartFrame();
        ob.show();
    }//GEN-LAST:event_schemePartButtonActionPerformed

    private void schemeSemesterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schemeSemesterButtonActionPerformed
        // TODO add your handling code here:
        SchemeSemesterFrame ob=new SchemeSemesterFrame();
        ob.show();
    }//GEN-LAST:event_schemeSemesterButtonActionPerformed

    private void schemeDetailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schemeDetailButtonActionPerformed
        // TODO add your handling code here:
        SchemeDetailFrame ob=new SchemeDetailFrame();
        ob.show();
    }//GEN-LAST:event_schemeDetailButtonActionPerformed

    private void schemeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schemeButtonActionPerformed
        // TODO add your handling code here:
        SchemeFrame ob=new SchemeFrame();
        ob.show();
    }//GEN-LAST:event_schemeButtonActionPerformed

    private void ledgerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ledgerButtonActionPerformed
        // TODO add your handling code here:
        LedgerFrame ob=new LedgerFrame();
        ob.show();
    }//GEN-LAST:event_ledgerButtonActionPerformed

    private void ledgerDetailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ledgerDetailButtonActionPerformed
        // TODO add your handling code here:
        LedgerDetailFrame ob=new LedgerDetailFrame();
        ob.show();
    }//GEN-LAST:event_ledgerDetailButtonActionPerformed

    private void ledgerDetailSummaryButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ledgerDetailSummaryButton1ActionPerformed
        // TODO add your handling code here:
        LedgerDetailSummaryFrame ob =  new LedgerDetailSummaryFrame();
        ob.show();
    }//GEN-LAST:event_ledgerDetailSummaryButton1ActionPerformed

    private void TeacherButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeacherButton1ActionPerformed
        // TODO add your handling code here:
        TeacherFrame  ob = new TeacherFrame();
        ob.show();
    }//GEN-LAST:event_TeacherButton1ActionPerformed

    private void timeTableButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeTableButton2ActionPerformed
        // TODO add your handling code here:
        TimeTableFrame ob  =  new TimeTableFrame();
        ob.show();
    }//GEN-LAST:event_timeTableButton2ActionPerformed

    private void AssignmentButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssignmentButton3ActionPerformed
        // TODO add your handling code here:d
        AssignmentFrame ob =  new AssignmentFrame();
        ob.show();
    }//GEN-LAST:event_AssignmentButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuperAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuperAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuperAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuperAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuperAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AssignmentButton3;
    private javax.swing.JButton TeacherButton1;
    private javax.swing.JButton batchButton;
    private javax.swing.JButton departmentButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton facultyButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton ledgerButton;
    private javax.swing.JButton ledgerDetailButton;
    private javax.swing.JButton ledgerDetailSummaryButton1;
    private javax.swing.JButton notifactionButton;
    private javax.swing.JButton partButton;
    private javax.swing.JButton programButton;
    private javax.swing.JButton schemeButton;
    private javax.swing.JButton schemeDetailButton;
    private javax.swing.JButton schemePartButton;
    private javax.swing.JButton schemeSemesterButton;
    private javax.swing.JButton seatListButton;
    private javax.swing.JButton seatListDetailButton;
    private javax.swing.JButton studentButton;
    private javax.swing.JButton studentPartButton;
    private javax.swing.JButton timeTableButton2;
    // End of variables declaration//GEN-END:variables
}
